name: Hexo Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install -g hexo-cli && npx hexo init mrzhao && cd mrzhao && pwd && ls
