name: Hexo Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install -g hexo-cli
      - run: npx hexo init mrzhao  
      - run: cd /home/runner/work/markdown/markdown/mrzhao
      - run: pwd  
      - run: ls
